gsap.from('#nav h3', {duration:1, ease:'expo.inOut', x:40, opacity:0})
gsap.from('#links  a', {stagger: .2,  duration:1, ease:'expo.inOut', x:40, opacity:0})
gsap.from('#righttop .ranim', {delay:1, stagger: .2,  duration:1, ease:'expo.inOut', x:40, opacity:0})
gsap.from('#right', {duration:2.5, ease:'expo.inOut', x:'100%', opacity:0})
gsap.from('#headings', {duration:2.5, ease:'expo.inOut', y:'40%', opacity:0})
gsap.from('#line', { duration:2.5, ease:'expo.inOut', width:'0%'})
gsap.from('#headings .manim', {stagger: .3,  duration:2, ease:'expo.inOut', y:'55%', opacity:0})
gsap.from('#credits img', {delay:1, stagger: .3,  duration:1, ease:'expo.inOut', y:'10%', opacity:0})
gsap.to('#right img', {delay:1, scale:1,  duration:1.5, ease:'expo.inOut', })
// gsap.from('#credits img', {delay:1, stagger: .3,  duration:1, ease:'expo.inOut', y:'10%', opacity:0})
